### ISSUE TITLE
Automated Light beam

### ISSUE THREAD

**Issue by kargaranamir** [princiya/lightbeam-import#2]
Hi, 
Thanks very much for your efforts in lightbeam project.
I want to use lightbeam for 10K websites , What do you suggest for our work ? 
 How do i automate this work?

**Comment by princiya** [comment]
Hi @kargaranamir could you elaborate a bit more about your project?

You can also email me princiya dot marina at the rate of gmail dot com

**Comment by kargaranamir** [comment]
Thanks for your response. I just realize that i got a response from you. 
In my thesis, i focused on machine learning applications for detecting trackers using feature extraction from the graph connectivity ( like the output of lightbeam).
I crawled first 10K websites ranked in Alexa using [Splash](http://splash.readthedocs.io). ( a headless browser can extract requested URLs from a crawled site)
and process them to make a graph.

Now, I want to use lightbeam for creating this graph.
How can i use it automatically for 10K websites? Cpu and memory are limited.
Have you any suggestion?

**Comment by princiya** [comment]
@kargaranamir Lightbeam does not support your use-case. Maybe OpenWPM will help you? https://github.com/mozilla/OpenWPM
